### ISSUE TITLE
1000 User Akses Bersamaan Butuh 16 CPU, Apakah Wajar?

### ISSUE THREAD

**Issue by almazary** [ProgrammerZamanNow/qna#666]
halo pak eko, 

saya memiliki aplikasi web ujian online yang dibuat menggunakan laravel versi 6, database mysql, dan berjalan di nginx php-fpm. nah ketika ingin digunakan untuk ujian bersamaan dengan user sekitar 1000 user, resource yang dibutuhkan harus minimal 16 CPU 32 RAM.

saya sudah melakukan optimasi query database, implementasi caching menggunakan redis, dan juga menyesuaikan pengaturan max children php-fpm.

nah pertanyaan saya, apakah hal tersebu normal? apa mestinya bisa lebih dari itu dengan spesifikasi resource tersebut.

terima kasih pak, semoga rejeki saya bisa dijawab langsung oleh pak eko.

**Comment by sonarta** [comment]
izin menjawab ya, sepertinya itu kurang wajar ya, karena dengan spesifikasi seperti itu seharusnya bisa menangani lebih dari 1000 concurrent user dengan baik jika di optimalkan.
saya rasa mungkin masalahnya di optimisasinya, saran saya coba di identifikasi menggunakan monitoring tool untuk mengidentifikasi bottleneck nya.

**Comment by khannedy** [comment]
https://youtu.be/czwe0T8G64k

**Comment by almazary** [comment]
@firdausriawan2 baik mas, terima kasih ya sarannya.

@khannedy wah terima kasih banyak pak atas jawabannya... sepertinya memang harus meluangkan waktu untuk ngelunasin hutang upgrade ke laravel versi terbaru, dan memikirkan untuk support horizontal scaling.

**Comment by bryanagamk** [comment]
Maaf izin nimbrung pak @khannedy @almazary 

Saya juga mengalami kasus yang sama, aplikasi laravel saya selalu di scale secara vertical dengan menambah CPU dan RAM

Aplikasi saya ini semacam aplikasi omni channel untuk berbagai marketplace

Permasalahan yang saya hadapi saat menggunakan laravel
- Job dan listener yang banyak bekerja di background
- Saat menambahkan job baru terjadi error karena too many files open
- CPU dan RAM selalu tinggi walaupun kondisi aplikasi

Kondisi saat ini:
Aplikasi hanya berjalan di 1 VM.
Database sudah dilakukan indexing, solusi saat ini meningkatkan kapasitas RAM dan CPU 

Pertanyaan saya, bagaimana cara mengidentifikasi root cause dari problem ini dan strategi apa saja yang perlu ya pak. 

Terima kasih
Izin belajar, semoga ada rezeki yang mau bantu jawab

**Comment by bagaswh** [comment]
Izin ngasih sedikit insight dari pengalaman.

Sepengalaman saya, CPU usage aplikasi PHP yang tinggi karena dua hal: 

- OPCache tidak enabled atau tidak berjalan dengan baik 

- Aplikasi banyak hit external dependensi yang pakai HTTPS. Karena PHP tidak bisa maintain TLS session (CMIIW), maka harus terjadi TLS handshake setiap kali hit HTTPS dependency tersebut 

Paling gampang coba di-profile pakai tool FlameGraph by Brendan Gregg ini: https://github.com/brendangregg/FlameGraph. Tool ini di-run ketika traffic peak, nanti dia akan menghasilkan "flamegraph", yang menunjukkan function mana yang paling berat di-execute. Function di sini bukan function PHP Anda atau library ya, melainkan function yang dipanggil sama si interpreter C PHP-nya (https://github.com/php/php-src). Kalo di generated FlameGraph-nya ada stack frame dengan label seperti "zendparse" atau "ssl" yang panjang, maka hampir bisa dipastikan itu memang karena OPCache tidak well-configured atau TLS handshake.
